// Generated by CoffeeScript 1.4.0
var LeaderBoardLayout, LeaderItemView, LeaderList, LeaderSheet,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

LeaderBoardLayout = (function(_super) {

  __extends(LeaderBoardLayout, _super);

  function LeaderBoardLayout() {
    return LeaderBoardLayout.__super__.constructor.apply(this, arguments);
  }

  LeaderBoardLayout.prototype.template = '#leader-layout';

  LeaderBoardLayout.prototype.regions = {
    list: '.leader-list'
  };

  LeaderBoardLayout.prototype.initialize = function() {
    this.leaders = new LeaderSheet;
    return this.listenTo(this.leaders, 'sync', this.showLeaders);
  };

  LeaderBoardLayout.prototype.onRender = function() {
    return this.leaders.fetch();
  };

  LeaderBoardLayout.prototype.showLeaders = function() {
    var players,
      _this = this;
    this.leaderData = [];
    _.each(this.leaders.get('feed')['entry'], function(cell, idx) {
      var response, score;
      score = cell.content['$t'].replace('_cokwr: ', '');
      response = {
        place: idx,
        name: cell.title['$t'],
        score: score
      };
      return _this.leaderData.push(response);
    });
    players = new Backbone.Collection(this.leaderData);
    return this.list.show(new LeaderList({
      collection: players
    }));
  };

  return LeaderBoardLayout;

})(Backbone.Marionette.Layout);

LeaderItemView = (function(_super) {

  __extends(LeaderItemView, _super);

  function LeaderItemView() {
    return LeaderItemView.__super__.constructor.apply(this, arguments);
  }

  LeaderItemView.prototype.template = '#leader-item';

  LeaderItemView.prototype.className = 'leader-deets';

  LeaderItemView.prototype.initialize = function() {
    var place;
    place = this.model.get('place');
    return this.$el.addClass("p" + place);
  };

  return LeaderItemView;

})(Backbone.Marionette.ItemView);

LeaderList = (function(_super) {

  __extends(LeaderList, _super);

  function LeaderList() {
    return LeaderList.__super__.constructor.apply(this, arguments);
  }

  LeaderList.prototype.itemView = LeaderItemView;

  LeaderList.prototype.className = 'weiners';

  return LeaderList;

})(Backbone.Marionette.CollectionView);

LeaderSheet = (function(_super) {

  __extends(LeaderSheet, _super);

  function LeaderSheet() {
    return LeaderSheet.__super__.constructor.apply(this, arguments);
  }

  LeaderSheet.prototype.url = "https://spreadsheets.google.com/feeds/list/0AmkZRXO39XOSdFh6ZzFqWng1dHRLRXk0NmlTekdHYWc/2/public/basic?alt=json";

  return LeaderSheet;

})(Backbone.Model);

$(document).ready(function() {
  var lb;
  lb = new LeaderBoardLayout({
    el: "#leaderboard"
  });
  return lb.render();
});
